### ISSUE TITLE
FileNotFoundError: Could not find module 'E:\gitstore\pointnet.pytorch-master\utils\render_balls_so.dll' (or one of its dependencies). Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by liuzhihaozhengshuai** [fxia22/pointnet.pytorch#104]
PS E:\gitstore\pointnet.pytorch-master\utils> python show_seg.py --model seg/seg_model_Chair_4.pth --dataset=E:\gitstore\pointnet.pytorch-master\shapenetcore_partanno_segmentation_benchmark_v0 --class_choice Earphone --idx 1
Traceback (most recent call last):
  File "E:\gitstore\pointnet.pytorch-master\utils\show_seg.py", line 2, in <module>
    from show3d_balls import showpoints
  File "E:\gitstore\pointnet.pytorch-master\utils\show3d_balls.py", line 23, in <module>
    dll=np.ctypeslib.load_library(r'E:\gitstore\pointnet.pytorch-master\utils\render_balls_so.dll','.')
  File "D:\anaconda\lib\site-packages\numpy\ctypeslib.py", line 158, in load_library
    return ctypes.cdll[libpath]
  File "D:\anaconda\lib\ctypes\__init__.py", line 449, in __getitem__
    return getattr(self, name)
  File "D:\anaconda\lib\ctypes\__init__.py", line 444, in __getattr__
    dll = self._dlltype(name)
  File "D:\anaconda\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'E:\gitstore\pointnet.pytorch-master\utils\render_balls_so.dll' (or one of its dependencies). Try using the full path with constructor syntax.

but the file render_balls_so.dll already existence and located in the correct path

**Comment by liuzhihaozhengshuai** [comment]
I have resolved this issue, which is caused by the missing DLL file, file render_ Balls_ So.dll requires four DLL files, kernel32.dll and libgcc_ S_ Seh-1.dll, libstdc++-6.dll, msvcrt.dll, from the website https://cn.dll-files.com/ You can download them, and after downloading, place these DLL files in render_ Balls_ The folder where the so.dll file is located (the "utils" folder) can solve the above problem

**Comment by liuzhihaozhengshuai** [comment]
我已经解决了这个问题，这是因为缺少dll文件导致的，文件render_balls_so.dll需要四个dll文件，kernel32.dll，libgcc_s_seh-1.dll，libstdc++-6.dll，msvcrt.dll，从网站https://cn.dll-files.com/可以下载他们，下载好后，将这些dll文件放在render_balls_so.dll文件所在的文件夹（"utils"文件夹）就能解决上述问题了

**Comment by NULLsalanghae** [comment]
In my case, I solved this problem using 'os.add_dll_directory' instead 'cdll.LoadLibrary' in 'show3d_balls.py'.
My env is constructed with Python3.8 which is changed how to load dll file.
Here are some links that have helped me:
https://stackoverflow.com/questions/59330863/cant-import-dll-module-in-python/64472088#64472088
https://docs.python.org/3/whatsnew/3.8.html#ctypes
