### ISSUE TITLE
please help to solve this issue

### ISSUE THREAD

**Issue by gollakousik123** [fxia22/pointnet.pytorch#11]
![image](https://user-images.githubusercontent.com/22300406/36382969-b9567ffc-15b0-11e8-90a5-3a5ef5c0cf01.png)

**Comment by gollakousik123** [comment]
im using pytorch 0.3.1

**Comment by gollakousik123** [comment]
torchvision 0.2.0

**Comment by nitinagarwal** [comment]
I also have the same versions and facing the same issue. 
what versions did you (@fxia22 ) use. 

thanks

**Comment by nitinagarwal** [comment]
pytorch 2.0 worked.

**Comment by fxia22** [comment]
For your reference, my software stack versions are listed here #13

**Comment by cissy123** [comment]
Can I take a look at your log? Mine is weird. Like this...

[8: 85/199] train loss: 0.003939 accuracy: 1.000000
[8: 86/199] train loss: 0.002299 accuracy: 1.000000
[8: 87/199] train loss: 0.034110 accuracy: 0.000000
[8: 88/199] train loss: 0.006786 accuracy: 1.000000
[8: 89/199] train loss: 0.047767 accuracy: 0.000000
[8: 90/199] train loss: 0.007080 accuracy: 1.000000
[8: 90/199] test loss: 0.038681 accuracy: 0.000000
[8: 91/199] train loss: 0.012933 accuracy: 1.000000
[8: 92/199] train loss: 0.008747 accuracy: 1.000000
[8: 93/199] train loss: 0.027482 accuracy: 0.000000
[8: 94/199] train loss: 0.026356 accuracy: 0.000000
[8: 95/199] train loss: 0.083937 accuracy: 0.000000
[8: 96/199] train loss: 0.013348 accuracy: 1.000000
[8: 97/199] train loss: 0.003802 accuracy: 1.000000
[8: 98/199] train loss: 0.003153 accuracy: 1.000000
[8: 99/199] train loss: 0.070998 accuracy: 0.000000
[8: 100/199] train loss: 0.006049 accuracy: 1.000000

**Comment by 3bobo** [comment]
I have the same error, and my data are all zero and with some error :
```
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fd712dc8f28>>
Traceback (most recent call last):
  File "/home/zqk/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/zqk/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/zqk/anaconda2/envs/torch3.7/lib/python3.5/multiprocessing/queues.py", line 337, in get
    return ForkingPickler.loads(res)
  File "/home/zqk/.local/lib/python3.5/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/zqk/anaconda2/envs/torch3.7/lib/python3.5/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/zqk/anaconda2/envs/torch3.7/lib/python3.5/multiprocessing/reduction.py", line 181, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/zqk/anaconda2/envs/torch3.7/lib/python3.5/multiprocessing/reduction.py", line 152, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))
ConnectionResetError: [Errno 104] Connection reset by peer
[0: 1377/15990] train loss: 0.000000 accuracy: 0.000000
[0: 1378/15990] train loss: 0.000000 accuracy: 0.000000
[0: 1379/15990] train loss: 0.000000 accuracy: 0.000000
[0: 1380/15990] train loss: 0.000000 accuracy: 0.000000
[0: 1380/15990] test loss: 0.000000 accuracy: 0.000000
[0: 1381/15990] train loss: 0.000000 accuracy: 0.000000
[0: 1382/15990] train loss: 0.000000 accuracy: 0.000000
[0: 1383/15990] train loss: 0.000000 accuracy: 0.000000
[0: 1384/15990] train loss: 0.000000 accuracy: 0.000000
[0: 1385/15990] train loss: 0.000000 accuracy: 0.000000
```
my pytorch vision is 0.4.1 ,and torchvision is 0.2.1, python 3.5

**Comment by 3bobo** [comment]
@mxg007 what's your batch size in show_cls.py?

**Comment by 3bobo** [comment]
@mxg007 what's your batch size in show_cls.py
