### ISSUE TITLE
how to get ModelNet40

### ISSUE THREAD

**Issue by Helena2007** [fxia22/pointnet.pytorch#110]
From where will we get modelnet40 dataset. I have tried manually downloading modelnet40, but when run the command got errors.

python3 train_classification.py --dataset /.../ModelNet40 --nepoch=10 --dataset_type modelnet40
Namespace(batchSize=32, num_points=2500, workers=4, nepoch=10, outf='cls', model='', dataset='home/.../ModelNet40', dataset_type='modelnet40', feature_transform=False)
Random Seed: 2348
Traceback (most recent call last):
File "/.../pointnet.pytorch/utils/train_classification.py", line 57, in
dataset = ModelNetDataset(
^^^^^^^^^^^^^^^^
File "/..../pointnet.pytorch/pointnet/dataset.py", line 154, in init
with open(os.path.join(root, '{}.txt'.format(self.split)), 'r') as f:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/...../ModelNet40/trainval.txt'

**Comment by Licolas** [comment]
I have the same question

**Comment by Licolas** [comment]
https://drive.google.com/drive/folders/1_fBYbDO3XSdRt3DSbEBe41r5l9YpIGWF
hey guy, maybe you can download dataset here

**Comment by mrhe13** [comment]
i also have this problem
