### ISSUE TITLE
OSError: no file with expected extension

### ISSUE THREAD

**Issue by mxg007** [fxia22/pointnet.pytorch#26]
when I run train_classification.py, there is an error:

F:\anaconda1\python.exe C:/Users/123456/Desktop/PointNet/pointnet_pytorch-master_lingzhang1/show3d_balls.py
Traceback (most recent call last):
  File "C:/Users/123456/Desktop/PointNet/pointnet_pytorch-master_lingzhang1/show3d_balls.py", line 19, in <module>
    dll=np.ctypeslib.load_library('render_balls_so','.')
  File "F:\anaconda1\lib\site-packages\numpy\ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

**Comment by feifeiwei** [comment]
I have meet the same problem.  Have you solved it?

**Comment by AlphaPav** [comment]
I solved the problem by changing `dll=np.ctypeslib.load_library('render_balls_so','.')` into `dll = np.ctypeslib.load_library('render_balls_so.so', '.')`

**Comment by cheulyop** [comment]
> I solved the problem by changing `dll=np.ctypeslib.load_library('render_balls_so','.')` into `dll = np.ctypeslib.load_library('render_balls_so.so', '.')`

same problem here and the above workaround doesn't seem to work for me.
maybe the issue is that I'm trying to run the code on google colab, but I can't be sure.

**Comment by dream-toy** [comment]
> I solved the problem by changing `dll=np.ctypeslib.load_library('render_balls_so','.')` into `dll = np.ctypeslib.load_library('render_balls_so.so', '.')`

Thanks a lot!!!

**Comment by zsl4399** [comment]
> 我通过`dll=np.ctypeslib.load_library('render_balls_so','.')`改成解决了这个问题`dll = np.ctypeslib.load_library('render_balls_so.so', '.')`


我用此方法试过了，可是我这里行不通

**Comment by FandosA** [comment]
> > I solved the problem by changing `dll=np.ctypeslib.load_library('render_balls_so','.')` into `dll = np.ctypeslib.load_library('render_balls_so.so', '.')`

I've tried this on windows and it's been impossible. But I tried this solution in linux and it worked immediately.

**Comment by AIllIll** [comment]
> > > I solved the problem by changing `dll=np.ctypeslib.load_library('render_balls_so','.')` into `dll = np.ctypeslib.load_library('render_balls_so.so', '.')`
> 
> I've tried this on windows and it's been impossible. But I tried this solution on linux and it worked immediately.

try to use absolute path like "home/xxx/pointnet.pytorch/utils/" instead of '.'
