### ISSUE TITLE
Error running train_classification.py: freeze support

### ISSUE THREAD

**Issue by abnerrjo** [fxia22/pointnet.pytorch#64]
While running the script `utils/train_classification.py` on Windows, I bump into the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File ".\train_classification.py", line 104, in <module>
    exitcode = _main(fd)
    for i, data in enumerate(dataloader, 0):
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    prepare(preparation_data)
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    _fixup_main_from_path(data['init_main_from_path'])
    w.start()
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    run_name="__mp_main__")
    self._popen = self._Popen(self)
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    pkg_name=pkg_name, script_name=fname)
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    mod_name, mod_spec, pkg_name, script_name)
    return Popen(process_obj)
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    exec(code, run_globals)
    reduction.dump(process_obj, to_child)
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
  File "C:\Users\abner\Documents\Github\pointnet.pytorch\utils\train_classification.py", line 104, in <module>
    ForkingPickler(file, protocol).dump(obj)
    for i, data in enumerate(dataloader, 0):
BrokenPipeError: [Errno 32] Broken pipe
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\abner\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by timothylimyl** [comment]
to those that are lazy to check the code merge:

Go to `train_classification.py` , add `from torch.multiprocessing import freeze_support`  then put everything within `if __name__ == "__main__":`

**Comment by hmfjx123** [comment]
change the num_workers from 4 to 0

**Comment by FandosA** [comment]
> 
> 
> change the num_workers from 4 to 0

This solve the problem, thank you!
