### ISSUE TITLE
Hellow,.How can we get ply of modelnet40? what can you explain? 

### ISSUE THREAD

**Issue by sunjunling666** [fxia22/pointnet.pytorch#76]

**Comment by timothylimyl** [comment]
hey, having the same problem:

```   
with open(os.path.join(self.root, fn), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/ModelNet40\\cone/train/cone_0073.ply'
```

All the files from ModelNet40 is .off files.

**Comment by comewei** [comment]
yes,I also meet.It's so sad.

**Comment by lmomoy** [comment]
> yes,I also meet.It's so sad.

Have you solved it?

**Comment by comewei** [comment]
> > yes,I also meet.It's so sad.
> 
> Have you solved it?

hello,then I just use the `bash download.sh`.it all finish.first, i set my code in Windows,it doesn't work. so i change the OS into Ubuntu,it really works. wish it be helpful.

**Comment by lmomoy** [comment]
> > > yes,I also meet.It's so sad.
> > 
> > 
> > Have you solved it?
> 
> hello,then I just use the `bash download.sh`.it all finish.first, i set my code in Windows,it doesn't work. so i change the OS into Ubuntu,it really works. wish it be helpful.

I guess that the download.sh only is the source of segmentation dataset instead of modelnet40. Do you use the segmentation dataset?

**Comment by comewei** [comment]
> > > > yes,I also meet.It's so sad.
> > > 
> > > 
> > > Have you solved it?
> > 
> > 
> > hello,then I just use the `bash download.sh`.it all finish.first, i set my code in Windows,it doesn't work. so i change the OS into Ubuntu,it really works. wish it be helpful.
> 
> I guess that the download.sh only is the source of segmentation dataset instead of modelnet40. Do you use the segmentation dataset?

hello,sorry,I don't solve it.

**Comment by Helena2007** [comment]
download.sh contains information about shapenet dataset only. From where will we get modelnet40 dataset. I have tried manually downloading modelnet40, but when run the command got errors. 

python3 train_classification.py --dataset /.../ModelNet40  --nepoch=10 --dataset_type modelnet40
Namespace(batchSize=32, num_points=2500, workers=4, nepoch=10, outf='cls', model='', dataset='home/.../ModelNet40', dataset_type='modelnet40', feature_transform=False)
Random Seed:  2348
Traceback (most recent call last):
  File "/.../pointnet.pytorch/utils/train_classification.py", line 57, in <module>
    dataset = ModelNetDataset(
              ^^^^^^^^^^^^^^^^
  File "/..../pointnet.pytorch/pointnet/dataset.py", line 154, in __init__
    with open(os.path.join(root, '{}.txt'.format(self.split)), 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/...../ModelNet40/trainval.txt'

**Comment by talxhaaa** [comment]
apparently the dataset is offline and the manually downloaded one doesn't have the same directory buildup as the one in the repository sadly
